import { useMemo, useState, type FormEvent } from "react";

import type { FinanceAccount, FinanceGoal, FinanceGoalTimeframe, FinanceGoalType, FinanceTransaction } from "../../../database/db";
import { accountTypeLabel } from "../financeCatalog";
import { formatMoney } from "../services/financeCalculations";
import { getFinanceGoalProgress, type FinanceGoalInput } from "../services/financeGoalService";

interface Props {
  now: Date;
  accounts: FinanceAccount[];
  transactions: FinanceTransaction[];
  goals: FinanceGoal[];
  onCreate: (input: FinanceGoalInput) => Promise<void>;
  onUpdate: (id: number, input: FinanceGoalInput) => Promise<void>;
  onDelete: (goal: FinanceGoal) => Promise<void>;
}

function dateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function timeframeLabel(value: FinanceGoalTimeframe) { return value === "monthly" ? "This month" : value === "yearly" ? "This year" : "Custom deadline"; }

function GoalEditor({ now, accounts, goal, onClose, onSave, onDelete }: { now: Date; accounts: FinanceAccount[]; goal: FinanceGoal | null; onClose: () => void; onSave: (input: FinanceGoalInput) => Promise<void>; onDelete?: () => Promise<void> }) {
  const [goalType, setGoalType] = useState<FinanceGoalType>(goal?.goalType ?? "balance");
  const eligible = accounts.filter((item) => item.type !== "credit" && (goalType === "balance" || ["savings", "investment", "retirement"].includes(item.type)));
  const initialAccount = eligible.some((item) => item.id === goal?.accountId) ? goal!.accountId : eligible[0]?.id ?? 0;
  const [name, setName] = useState(goal?.name ?? ""); const [target, setTarget] = useState(goal?.targetAmount ? String(goal.targetAmount) : ""); const [accountId, setAccountId] = useState(initialAccount);
  const [timeframe, setTimeframe] = useState<FinanceGoalTimeframe>(goal?.timeframe ?? "yearly"); const [deadline, setDeadline] = useState(goal?.deadline ?? dateKey(new Date(now.getFullYear(), 11, 31)));
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await onSave({ name, goalType, targetAmount: Number(target.replace(/[$,\s]/g, "")), accountId, timeframe, startDate: goal?.startDate ?? dateKey(now), deadline: timeframe === "custom" ? deadline : undefined }); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save this goal."); } finally { setSaving(false); } }
  return <div className="finance-modal-layer"><button className="finance-modal-backdrop" type="button" aria-label="Close goal editor" onClick={onClose} /><form className="finance-modal finance-goal-modal" onSubmit={submit}><header><div><span className="text-label">Intent made visible</span><h2>{goal ? "Edit goal" : "New financial goal"}</h2></div><button type="button" onClick={onClose}>×</button></header><div className="finance-modal-fields"><label className="finance-field-wide"><span>Goal name</span><input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Build the HYSA to $25,000" /></label><label><span>Goal type</span><select value={goalType} onChange={(event) => { const next = event.target.value as FinanceGoalType; setGoalType(next); const nextEligible = accounts.filter((item) => item.type !== "credit" && (next === "balance" || ["savings", "investment", "retirement"].includes(item.type))); if (!nextEligible.some((item) => item.id === accountId)) setAccountId(nextEligible[0]?.id ?? 0); }}><option value="balance">Balance goal</option><option value="contribution">Contribution goal</option></select><small>{goalType === "balance" ? "Uses the account's live balance." : "Uses transfers and investments into the account."}</small></label><label><span>Linked account</span><select value={accountId} onChange={(event) => setAccountId(Number(event.target.value))}>{eligible.length ? eligible.map((item) => <option key={item.id} value={item.id}>{item.name} · {accountTypeLabel(item.type)}</option>) : <option value={0}>No eligible accounts</option>}</select></label><label><span>Target amount</span><div className="finance-money-input"><i>$</i><input inputMode="decimal" value={target} onChange={(event) => setTarget(event.target.value)} placeholder="0.00" /></div></label><label><span>Timeframe</span><select value={timeframe} onChange={(event) => setTimeframe(event.target.value as FinanceGoalTimeframe)}><option value="monthly">Monthly</option><option value="yearly">Yearly</option><option value="custom">Custom deadline</option></select></label>{timeframe === "custom" && <label className="finance-field-wide"><span>Deadline</span><input type="date" min={goal?.startDate ?? dateKey(now)} value={deadline} onChange={(event) => setDeadline(event.target.value)} /></label>}{error && <small className="finance-field-wide is-negative">{error}</small>}</div><footer>{onDelete && <button className="is-danger" type="button" onClick={onDelete}>Archive goal</button>}<span /><button type="button" onClick={onClose}>Cancel</button><button type="submit" disabled={saving || !eligible.length}>{saving ? "Saving…" : "Save goal"}</button></footer></form></div>;
}

export default function FinanceGoals({ now, accounts, transactions, goals, onCreate, onUpdate, onDelete }: Props) {
  const [editor, setEditor] = useState<FinanceGoal | "new" | null>(null);
  const rows = useMemo(() => goals.map((goal) => ({ goal, account: accounts.find((item) => item.id === goal.accountId), progress: getFinanceGoalProgress(goal, accounts, transactions, now) })), [accounts, goals, now, transactions]);
  const completed = rows.filter((item) => item.progress.percentage >= 100).length;
  return <section className="finance-goals-view"><header className="finance-section-heading"><div><span className="text-label">Direction over pressure</span><h2>Goals</h2><p>Connect intentions to the balances and contributions Momentum already understands.</p></div><button className="finance-primary-action" type="button" onClick={() => setEditor("new")}>＋ New goal</button></header>{rows.length ? <><section className="finance-goal-summary finance-panel"><div><span>Active goals</span><strong>{rows.length}</strong></div><div><span>Reached</span><strong>{completed}</strong></div><p>Progress updates from the ledger. You never need to enter it twice.</p></section><div className="finance-goal-grid">{rows.map(({ goal, account, progress }, index) => { const reached = progress.percentage >= 100; return <button type="button" className={`finance-goal-card finance-panel ${reached ? "is-complete" : ""}`} key={goal.id} onClick={() => setEditor(goal)}><header><span className="finance-goal-index">{String(index + 1).padStart(2, "0")}</span><span>{goal.goalType === "balance" ? "Balance" : "Contribution"}</span><em>{timeframeLabel(goal.timeframe)}</em></header><h3>{goal.name}</h3><p>{account?.name ?? "Missing account"}</p><div className="finance-goal-progress"><i><span style={{ width: `${Math.min(100, progress.percentage)}%` }} /></i><strong>{Math.round(progress.percentage)}%</strong></div><footer><div><span>Current</span><strong>{formatMoney(progress.current)}</strong></div><div><span>{reached ? "Beyond target" : "Remaining"}</span><strong>{formatMoney(reached ? progress.current - goal.targetAmount : progress.remaining)}</strong></div><div><span>Target</span><strong>{formatMoney(goal.targetAmount)}</strong></div></footer>{goal.goalType === "contribution" && !reached && <small className={progress.onTrack ? "is-positive" : ""}>{progress.onTrack ? `On pace for ${formatMoney(progress.projected ?? 0)}` : `Current pace projects ${formatMoney(progress.projected ?? 0)}`}</small>}</button>; })}</div></> : <section className="finance-goal-empty finance-panel"><span>◎</span><h3>Give your money somewhere to go.</h3><p>Start with one meaningful target. Momentum will calculate progress from your accounts and transactions.</p><button type="button" onClick={() => setEditor("new")}>Create your first goal →</button></section>}{editor && <GoalEditor key={editor === "new" ? "new" : editor.id} now={now} accounts={accounts} goal={editor === "new" ? null : editor} onClose={() => setEditor(null)} onSave={(input) => editor === "new" ? onCreate(input) : onUpdate(editor.id!, input)} onDelete={editor !== "new" ? async () => { await onDelete(editor); setEditor(null); } : undefined} />}</section>;
}
