import { useState } from "react";

import type { FinanceAccount, FinanceCategory, FinanceTransaction } from "../../../database/db";
import { formatMoney, isTransactionHiddenFromLedger, transactionSignedAmount } from "../services/financeCalculations";

type Visibility = "visible" | "all" | "hidden";
interface Props { accounts: FinanceAccount[]; categories: FinanceCategory[]; transactions: FinanceTransaction[]; onImport: () => void; onEdit: (item: FinanceTransaction) => void; onDelete: (item: FinanceTransaction) => Promise<void>; onSetVisibility: (item: FinanceTransaction, hidden: boolean) => Promise<void>; }

export default function FinanceTransactions({ accounts, categories, transactions, onImport, onEdit, onDelete, onSetVisibility }: Props) {
  const [search, setSearch] = useState(""); const [type, setType] = useState("all"); const [month, setMonth] = useState("all"); const [merchant, setMerchant] = useState("all"); const [accountId, setAccountId] = useState("all"); const [categoryId, setCategoryId] = useState("all"); const [visibility, setVisibility] = useState<Visibility>("visible");
  const accountMap = new Map(accounts.map((item) => [item.id, item.name])); const categoryMap = new Map(categories.map((item) => [item.id, item.name]));
  const hiddenCount = transactions.filter(isTransactionHiddenFromLedger).length;
  const months = [...new Set(transactions.map((item) => item.date.slice(0, 7)))].sort((a, b) => b.localeCompare(a)); const merchants = [...new Set(transactions.map((item) => item.merchant).filter(Boolean))].sort((a, b) => a.localeCompare(b));
  const filtered = transactions.filter((item) => {
    const category = categoryMap.get(item.categoryId) ?? item.category ?? ""; const accountNames = item.type === "transfer" ? `${accountMap.get(item.fromAccountId) ?? ""} ${accountMap.get(item.toAccountId) ?? ""}` : accountMap.get(item.accountId) ?? "";
    const haystack = `${item.merchant} ${category} ${accountNames} ${item.notes ?? ""}`.toLocaleLowerCase(); const selectedAccountId = Number(accountId);
    const hidden = isTransactionHiddenFromLedger(item); const visibilityMatches = visibility === "all" || (visibility === "hidden" ? hidden : !hidden);
    return visibilityMatches && (type === "all" || item.type === type) && (month === "all" || item.date.startsWith(month)) && (merchant === "all" || item.merchant === merchant) && (categoryId === "all" || item.categoryId === Number(categoryId)) && (accountId === "all" || item.accountId === selectedAccountId || item.fromAccountId === selectedAccountId || item.toAccountId === selectedAccountId) && haystack.includes(search.trim().toLocaleLowerCase());
  }).sort((a, b) => b.date.localeCompare(a.date) || b.createdAt.localeCompare(a.createdAt));
  const hasFilters = Boolean(search.trim()) || type !== "all" || month !== "all" || merchant !== "all" || accountId !== "all" || categoryId !== "all" || visibility !== "visible"; const incoming = filtered.reduce((total, item) => total + Math.max(0, transactionSignedAmount(item)), 0); const outgoing = filtered.reduce((total, item) => total + Math.max(0, -transactionSignedAmount(item)), 0); const net = incoming - outgoing;
  function clearFilters() { setSearch(""); setType("all"); setMonth("all"); setMerchant("all"); setAccountId("all"); setCategoryId("all"); setVisibility("visible"); }

  return <section className="finance-transactions-view">
    <header className="finance-section-heading"><div><span className="text-label">Ledger</span><h2>Transactions</h2><p>Every balance begins here.</p></div><div><button className="finance-import-button" type="button" onClick={onImport}>⇧ Import CSV</button><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search ledger…" /></div></header>
    <section className="finance-ledger-filters finance-panel" aria-label="Ledger filters">
      <label><span>Month</span><select value={month} onChange={(event) => setMonth(event.target.value)}><option value="all">All months</option>{months.map((item) => <option key={item} value={item}>{new Date(`${item}-15T12:00:00`).toLocaleDateString("en-US", { month: "long", year: "numeric" })}</option>)}</select></label>
      <label><span>Merchant</span><select value={merchant} onChange={(event) => setMerchant(event.target.value)}><option value="all">All merchants</option>{merchants.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>
      <label><span>Category</span><select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="all">All categories</option>{categories.filter((item) => !item.deletedAt).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label><span>Account</span><select value={accountId} onChange={(event) => setAccountId(event.target.value)}><option value="all">All accounts</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label><span>Type</span><select value={type} onChange={(event) => setType(event.target.value)}><option value="all">All types</option><option value="expense">Expenses</option><option value="income">Income</option><option value="transfer">Transfers</option><option value="investment">Investments</option><option value="adjustment">Adjustments</option></select></label>
      <label><span>Visibility</span><select value={visibility} onChange={(event) => setVisibility(event.target.value as Visibility)}><option value="visible">Standard ledger</option><option value="all">Include hidden ({hiddenCount})</option><option value="hidden">Hidden only ({hiddenCount})</option></select></label>
      {hasFilters && <button type="button" onClick={clearFilters}>Clear</button>}
    </section>
    <div className="finance-transaction-table finance-panel"><header><span>Date</span><span>Merchant</span><span>Category</span><span>Account</span><span>Amount</span><span /></header>{filtered.length ? filtered.map((item) => {
      const signed = transactionSignedAmount(item); const hasRoute = item.type === "transfer" || item.type === "investment"; const account = hasRoute ? `${accountMap.get(item.fromAccountId) ?? "—"} → ${accountMap.get(item.toAccountId) ?? (item.type === "investment" ? "Needs investment account" : "—")}` : accountMap.get(item.accountId) ?? "—"; const category = categoryMap.get(item.categoryId) ?? item.category; const hidden = isTransactionHiddenFromLedger(item);
      return <article className={hidden ? "is-ledger-hidden" : ""} key={item.id} onDoubleClick={() => item.type !== "adjustment" && onEdit(item)}><time>{new Date(`${item.date}T12:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</time><div><span className={`finance-transaction-glyph type-${item.type}`}>{item.type === "income" ? "＋" : item.type === "transfer" ? "↔" : item.type === "investment" ? "↗" : item.type === "adjustment" ? "≈" : "−"}</span><strong>{item.merchant}</strong>{hidden && <small>Hidden</small>}</div><span>{category ?? (item.type === "transfer" ? "Transfer" : item.type === "adjustment" ? "Balance correction" : item.type)}</span><span className={item.type === "investment" && !item.toAccountId ? "is-negative" : ""}>{account}</span><b className={signed > 0 ? "is-positive" : signed < 0 ? "is-negative" : ""}>{item.type === "transfer" ? formatMoney(item.amount) : `${signed > 0 ? "+" : ""}${formatMoney(signed)}`}</b><menu>{item.type !== "adjustment" && <button type="button" onClick={() => onEdit(item)}>Edit</button>}<button type="button" onClick={() => onSetVisibility(item, !hidden)}>{hidden ? "Show" : "Hide"}</button><button type="button" onClick={() => onDelete(item)}>Delete</button></menu></article>;
    }) : <div className="finance-table-empty"><span>⌁</span><strong>No matching transactions.</strong><small>Adjust or clear the filters to widen the result.</small></div>}</div>
    {hasFilters && <footer className="finance-filter-total finance-panel"><div><span>Filtered result</span><strong>{filtered.length} {filtered.length === 1 ? "transaction" : "transactions"}</strong></div><div><span>Money in</span><strong className="is-positive">{formatMoney(incoming)}</strong></div><div><span>Money out</span><strong>{formatMoney(outgoing)}</strong></div><div><span>Net</span><strong className={net >= 0 ? "is-positive" : "is-negative"}>{net >= 0 ? "+" : ""}{formatMoney(net)}</strong></div></footer>}
  </section>;
}
