import { useState } from "react";

import type { FinanceAccount, FinanceBudgetAllocation, FinanceCategory, FinanceCategoryFlow, FinanceMonthlyReview, FinanceNetWorthSnapshot, FinanceTransaction } from "../../../database/db";
import { accountTypeLabel, financeFlowLabels, financeFlowOrder } from "../financeCatalog";
import { calculateMonthReviewRows, calculateYearReviewRows, shiftMonthKey } from "../services/financeBudgetService";
import { formatMoney, getAccountBalances, getCashFlowRange, getCategorySpending, getInvestmentContributionBreakdown, isBalanceTrackedAccount } from "../services/financeCalculations";

type Range = "3m" | "6m" | "ytd" | "1y" | "all";
type ReportScope = "month" | "year";
interface Props { now: Date; accounts: FinanceAccount[]; categories: FinanceCategory[]; allocations: FinanceBudgetAllocation[]; transactions: FinanceTransaction[]; snapshots: FinanceNetWorthSnapshot[]; reviews: FinanceMonthlyReview[]; onSaveSnapshot: () => Promise<void>; onDeleteSnapshot: (snapshot: FinanceNetWorthSnapshot) => Promise<void>; }
function cutoffFor(range: Range, now: Date) { if (range === "all") return "0000-00-00"; if (range === "ytd") return `${now.getFullYear()}-01-01`; const months = range === "3m" ? 3 : range === "6m" ? 6 : 12; const date = new Date(now.getFullYear(), now.getMonth() - months + 1, 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-01`; }
function chartPoints(values: number[], width = 680, height = 180) { if (!values.length) return ""; const min = Math.min(...values); const max = Math.max(...values); return values.map((value, index) => `${values.length === 1 ? width / 2 : index / (values.length - 1) * width},${height - ((value - min) / Math.max(1, max - min)) * (height - 28) - 14}`).join(" "); }
function currentMonth(now: Date) { return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`; }
function monthLabel(month: string) { const [year, number] = month.split("-").map(Number); return new Date(year, number - 1, 1).toLocaleDateString("en-US", { month: "long", year: "numeric" }); }

export default function FinanceReports({ now, accounts, categories: categoryRecords, allocations, transactions, snapshots, reviews, onSaveSnapshot, onDeleteSnapshot }: Props) {
  const [range, setRange] = useState<Range>("1y"); const [accountId, setAccountId] = useState<number | "all">("all"); const [month, setMonth] = useState(currentMonth(now)); const [scope, setScope] = useState<ReportScope>("month"); const [saving, setSaving] = useState(false);
  const [openFlows, setOpenFlows] = useState<Record<FinanceCategoryFlow, boolean>>({ expense: true, investment: false, income: false, saving: false });
  const filtered = snapshots.filter((item) => item.date >= cutoffFor(range, now)); const trackedAccounts = accounts.filter(isBalanceTrackedAccount); const currentBalances = getAccountBalances(trackedAccounts, transactions); const currentNetWorth = currentBalances.reduce((total, item) => total + item.balance, 0);
  const values = accountId === "all" ? filtered.map((item) => item.accounts.filter((account) => account.type !== "credit").reduce((total, account) => total + account.balance, 0)) : filtered.map((item) => item.accounts.find((account) => account.accountId === accountId)?.balance).filter((value): value is number => value !== undefined);
  const currentValue = accountId === "all" ? currentNetWorth : currentBalances.find((item) => item.account.id === accountId)?.balance ?? 0; const firstValue = values[0] ?? currentValue; const change = currentValue - firstValue;
  const year = Number(month.slice(0, 4)); const reportDate = scope === "year" ? new Date(year, 11, 15) : new Date(`${month}-15T12:00:00`); const flow = getCashFlowRange(transactions, reportDate, scope === "year" ? 12 : 6, categoryRecords); const categories = getCategorySpending(transactions, scope === "year" ? String(year) : month, categoryRecords); const flowMax = Math.max(1, ...flow.flatMap((item) => [item.income, item.expenses]));
  const reviewRows = scope === "year" ? calculateYearReviewRows(year, allocations, categoryRecords, transactions) : calculateMonthReviewRows(month, allocations, categoryRecords, transactions); const expenseRows = reviewRows.filter((row) => row.category.flowType === "expense" && (row.available > 0 || row.actual > 0)); const budgetMax = Math.max(1, ...expenseRows.flatMap((row) => [row.available, row.actual])); const savingsPoints = chartPoints(flow.map((item) => item.savingsRate), 680, 150);
  const reviewPlanned = reviewRows.filter((row) => row.category.flowType !== "income").reduce((total, row) => total + row.available, 0); const reviewActual = reviewRows.filter((row) => row.category.flowType !== "income").reduce((total, row) => total + row.actual, 0); const reviewIncome = reviewRows.filter((row) => row.category.flowType === "income").reduce((total, row) => total + row.actual, 0); const reviewRemaining = reviewPlanned - reviewActual; const reviewUsed = reviewPlanned ? reviewActual / reviewPlanned * 100 : 0;
  const categoryTotal = categories.reduce((total, item) => total + item.amount, 0); const topCategory = categories[0]; const topShare = topCategory && categoryTotal ? topCategory.amount / categoryTotal * 100 : 0;
  const annualIncome = flow.reduce((total, item) => total + item.income, 0); const annualExpenses = flow.reduce((total, item) => total + item.expenses, 0); const displayedSavingsRate = scope === "year" ? (annualIncome ? Math.max(0, (annualIncome - annualExpenses) / annualIncome * 100) : 0) : flow.at(-1)?.savingsRate ?? 0;
  const investmentBreakdown = getInvestmentContributionBreakdown(transactions, accounts, scope === "year" ? String(year) : month); const investmentMax = Math.max(1, ...investmentBreakdown.byAccount.map((item) => item.amount), ...investmentBreakdown.byHolding.map((item) => item.amount));
  const selectedReview = scope === "month" ? reviews.find((item) => item.month === month && item.closedAt) : undefined; const reflections = selectedReview ? [selectedReview.reflectionWentWell && ["What went well", selectedReview.reflectionWentWell], selectedReview.reflectionChange && ["What to change", selectedReview.reflectionChange], selectedReview.reflectionRemember && ["Worth remembering", selectedReview.reflectionRemember]].filter(Boolean) as string[][] : [];
  return <section className="finance-reports-view">
    <header className="finance-section-heading finance-reports-heading"><div><span className="text-label">History, preserved</span><h2>Reports</h2><p>Review a month or step back into the entire year without returning to a spreadsheet.</p></div><div className="finance-report-scope"><button type="button" className={scope === "month" ? "is-selected" : ""} onClick={() => setScope("month")}>Month</button><button type="button" className={scope === "year" ? "is-selected" : ""} onClick={() => setScope("year")}>Year</button></div></header>

    <section className="finance-month-review finance-panel">
      <header><div><span className="text-label">{scope === "year" ? "Annual perspective" : "Monthly truth"}</span><h3>{scope === "year" ? "Year in Review" : "Month in Review"}</h3><div className="finance-report-month"><button type="button" onClick={() => setMonth(scope === "year" ? `${year - 1}-${month.slice(5)}` : shiftMonthKey(month, -1))}>←</button><strong>{scope === "year" ? year : monthLabel(month)}</strong><button type="button" onClick={() => setMonth(scope === "year" ? `${year + 1}-${month.slice(5)}` : shiftMonthKey(month, 1))}>→</button></div></div><small>{scope === "year" ? "Monthly average uses the active portion of the selected year" : "Average compares the previous 3 completed months"}</small></header>
      <div className="finance-review-hero"><div className="finance-review-orbit" style={{ background: `conic-gradient(${reviewUsed > 100 ? "#a8736b" : "#89a992"} ${Math.min(100, reviewUsed)}%, rgba(255,255,255,.045) 0)` }}><div><strong>{reviewPlanned ? `${Math.round(reviewUsed)}%` : "—"}</strong><small>of plan</small></div></div><div><span className="text-label">The {scope === "year" ? "year" : "month"} at a glance</span><h4>{reviewRemaining >= 0 ? `${formatMoney(reviewRemaining)} still intentional.` : `${formatMoney(Math.abs(reviewRemaining))} beyond the plan.`}</h4><p>{reviewIncome ? `${formatMoney(reviewIncome)} received · ` : ""}{formatMoney(reviewActual)} directed across spending, investing, and saving.</p></div></div>
      <div className="finance-review-metrics"><article><span>Planned</span><strong>{formatMoney(reviewPlanned)}</strong><i /></article><article><span>Actual</span><strong>{formatMoney(reviewActual)}</strong><i /></article><article><span>Remaining</span><strong className={reviewRemaining >= 0 ? "is-positive" : "is-negative"}>{formatMoney(reviewRemaining)}</strong><i /></article><article><span>Income received</span><strong>{formatMoney(reviewIncome)}</strong><i /></article></div>
      <div className="finance-review-flows">{financeFlowOrder.map((flow) => {
        const rows = reviewRows.filter((row) => row.category.flowType === flow); const visibleRows = rows.filter((row) => row.available > 0 || row.actual > 0 || row.averageActual > 0); const planned = rows.reduce((total, row) => total + row.available, 0); const actual = rows.reduce((total, row) => total + row.actual, 0); const remaining = planned - actual; const percentage = planned ? actual / planned * 100 : 0;
        return <section className={`finance-review-flow flow-${flow} ${openFlows[flow] ? "is-open" : ""}`} key={flow}><button type="button" onClick={() => setOpenFlows((current) => ({ ...current, [flow]: !current[flow] }))}><span className="finance-review-flow-mark">{flow === "expense" ? "−" : flow === "income" ? "+" : flow === "investment" ? "↗" : "◇"}</span><div><strong>{financeFlowLabels[flow]}</strong><small>{formatMoney(actual)} actual · {planned ? `${Math.round(percentage)}% of plan` : "no plan set"}</small></div><i><b style={{ width: `${Math.min(100, percentage)}%` }} /></i><span><small>{flow === "income" ? "Difference" : "Remaining"}</small><strong className={flow !== "income" && remaining < 0 ? "is-negative" : ""}>{formatMoney(remaining)}</strong></span><em>{openFlows[flow] ? "−" : "+"}</em></button>{openFlows[flow] && <div className="finance-review-category-list">{visibleRows.map((row) => <article key={row.category.id}><header><strong>{row.category.name}</strong><span className={row.remaining < 0 && flow !== "income" ? "is-negative" : ""}>{row.remaining < 0 && flow !== "income" ? `${formatMoney(Math.abs(row.remaining))} over` : `${formatMoney(row.remaining)} left`}</span></header><div className="finance-review-category-track"><i style={{ width: `${Math.min(100, row.percentage)}%` }} /></div><footer><span>Planned<b>{formatMoney(row.available)}</b></span><span>Actual<b>{formatMoney(row.actual)}</b></span><span>Used<b>{row.available ? `${Math.round(row.percentage)}%` : "—"}</b></span><span>{scope === "year" ? "Monthly avg" : "3M average"}<b>{formatMoney(row.averageActual)}</b></span></footer></article>)}</div>}</section>;
      })}</div>
      {selectedReview && <section className="finance-closed-review"><header><span>✓ Closed {new Date(selectedReview.closedAt!).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</span><strong>{formatMoney(selectedReview.rolloverEarned)} carried forward</strong></header>{reflections.length ? <div>{reflections.map(([title, copy]) => <article key={title}><span>{title}</span><p>{copy}</p></article>)}</div> : <p>This month was closed without written reflections.</p>}</section>}
    </section>

    <div className="finance-report-grid"><section className="finance-panel finance-budget-actual"><header><div><span className="text-label">Plan versus reality</span><h3>Budget vs. actual</h3></div><small>Expenses</small></header>{expenseRows.length ? <div>{expenseRows.map((row) => <article key={row.category.id}><strong>{row.category.name}</strong><div><i className="planned" style={{ width: `${row.available / budgetMax * 100}%` }} /><i className="actual" style={{ width: `${row.actual / budgetMax * 100}%` }} /></div><span>{formatMoney(row.actual)} / {formatMoney(row.available)}</span></article>)}</div> : <p className="finance-empty-copy">Set an expense plan to begin comparing it.</p>}<footer><span><i className="planned" /> Planned</span><span><i className="actual" /> Actual</span></footer></section>
      <section className="finance-panel finance-savings-trend"><header><div><span className="text-label">Behavior over balance</span><h3>Savings rate</h3></div><strong>{displayedSavingsRate.toFixed(0)}%</strong></header><svg viewBox="0 0 680 150" preserveAspectRatio="none" role="img" aria-label={`${scope === "year" ? "Annual" : "Six month"} savings rate`}><defs><linearGradient id="finance-savings-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#91b49c" stopOpacity=".22"/><stop offset="1" stopColor="#91b49c" stopOpacity="0"/></linearGradient></defs>{savingsPoints && <polygon points={`0,150 ${savingsPoints} 680,150`} fill="url(#finance-savings-fill)" />}<line x1="0" y1="112" x2="680" y2="112" stroke="rgba(255,255,255,.07)" strokeDasharray="5 6" vectorEffect="non-scaling-stroke"/><polyline points={savingsPoints} fill="none" stroke="#9fbea9" strokeWidth="2" vectorEffect="non-scaling-stroke" />{flow.map((item, index) => { const point = savingsPoints.split(" ")[index]?.split(",") ?? [0, 0]; return <circle key={item.month} cx={point[0]} cy={point[1]} r={index === flow.length - 1 ? "5" : "3"} fill={index === flow.length - 1 ? "#d4e4d8" : "#9ab8a2"} />; })}</svg><footer>{flow.map((item) => <span key={item.month}>{item.label}<b>{item.savingsRate.toFixed(0)}%</b></span>)}</footer></section></div>

    <section className="finance-panel finance-investment-report"><header><div><span className="text-label">Capital in motion</span><h3>Investment contributions</h3></div><div><strong>{formatMoney(investmentBreakdown.total)}</strong><small>{scope === "year" ? year : monthLabel(month)}</small></div></header>{investmentBreakdown.total ? <div><section><h4>By account</h4>{investmentBreakdown.byAccount.map((item) => <article key={item.label}><span>{item.label}</span><i><b style={{ width: `${item.amount / investmentMax * 100}%` }} /></i><strong>{formatMoney(item.amount)}</strong></article>)}</section><section><h4>By holding</h4>{investmentBreakdown.byHolding.map((item) => <article key={item.label}><span>{item.label}</span><i><b style={{ width: `${item.amount / investmentMax * 100}%` }} /></i><strong>{formatMoney(item.amount)}</strong></article>)}</section></div> : <p className="finance-empty-copy">Investment contributions for this {scope} will gather here.</p>}</section>

    <section className="finance-report-hero finance-panel"><header><div><span className="text-label">{accountId === "all" ? "Net worth history" : "Account balance history"}</span><select value={accountId} onChange={(event) => setAccountId(event.target.value === "all" ? "all" : Number(event.target.value))}><option value="all">All accounts</option>{trackedAccounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><select aria-label="Net worth range" value={range} onChange={(event) => setRange(event.target.value as Range)}><option value="3m">3 months</option><option value="6m">6 months</option><option value="ytd">YTD</option><option value="1y">1 year</option><option value="all">All time</option></select><strong className="finance-balance-value">{formatMoney(currentValue)}</strong><small className={`${change >= 0 ? "is-positive" : "is-negative"} finance-balance-value`}>{change >= 0 ? "+" : ""}{formatMoney(change)} during period</small><button className="finance-save-snapshot" type="button" disabled={saving || !trackedAccounts.length} onClick={async () => { setSaving(true); try { await onSaveSnapshot(); } finally { setSaving(false); } }}>{saving ? "Saving…" : "Save snapshot"}</button></div></header><div className="finance-net-worth-chart"><svg viewBox="0 0 680 180" preserveAspectRatio="none" role="img" aria-label="Net worth and account history"><defs><linearGradient id="finance-chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7fae91" stopOpacity=".2"/><stop offset="1" stopColor="#7fae91" stopOpacity="0"/></linearGradient></defs>{values.length > 1 && <polygon points={`0,180 ${chartPoints(values)} 680,180`} fill="url(#finance-chart-fill)" />}<polyline points={chartPoints(values.length ? values : [currentValue])} fill="none" stroke="#8db89b" strokeWidth="2" vectorEffect="non-scaling-stroke" />{(values.length ? values : [currentValue]).map((value, index, list) => { const point = chartPoints(list).split(" ")[index].split(","); return <circle key={`${value}-${index}`} cx={point[0]} cy={point[1]} r="3" fill="#b5d2bf" />; })}</svg><footer>{filtered.length ? filtered.map((item) => <span key={item.id}>{new Date(`${item.date}T12:00:00`).toLocaleDateString("en-US", { month: "short", year: "2-digit" })}</span>) : <span>Save your first snapshot to begin history.</span>}</footer></div></section>

    <div className="finance-report-grid"><section className="finance-panel finance-report-accounts"><header><div><span className="text-label">Current position</span><h3>Account balances</h3></div><small>{trackedAccounts.length} accounts</small></header><div>{currentBalances.map(({ account, balance }) => { const earliest = filtered.map((item) => item.accounts.find((entry) => entry.accountId === account.id)?.balance).find((value) => value !== undefined); const delta = earliest === undefined ? 0 : balance - earliest; return <button type="button" key={account.id} onClick={() => setAccountId(account.id!)}><span className={`finance-account-dot type-${account.type}`} /><div><strong>{account.name}</strong><small>{accountTypeLabel(account.type)}</small></div><b className="finance-balance-value">{formatMoney(balance)}</b><i className={`${delta >= 0 ? "is-positive" : "is-negative"} finance-balance-value`}>{delta >= 0 ? "+" : ""}{formatMoney(delta, true)}</i></button>; })}</div></section>
      <section className="finance-panel finance-report-flow"><header><div><span className="text-label">Cash flow</span><h3>Income vs. spending</h3></div><small>{scope === "year" ? "Twelve months" : "Six months"}</small></header><div className="finance-report-bars">{flow.map((item) => <span key={item.month}><i className="income" style={{ height: `${item.income / flowMax * 100}%` }} /><i className="expense" style={{ height: `${item.expenses / flowMax * 100}%` }} /><small>{item.label}</small></span>)}</div><footer><span><i className="income" /> Income</span><span><i className="expense" /> Spending</span></footer></section></div>
    <div className="finance-report-grid"><section className="finance-panel finance-report-categories"><header><div><span className="text-label">{scope === "year" ? year : monthLabel(month)}</span><h3>Spending constellation</h3></div></header>{categories.length ? <><div className="finance-category-orbit" style={{ background: `conic-gradient(#8cab94 ${topShare}%, #5f6e64 ${topShare}% ${Math.min(100, topShare + (categories[1]?.amount ?? 0) / categoryTotal * 100)}%, rgba(255,255,255,.055) 0)` }}><div><strong>{topCategory.category}</strong><span>{topShare.toFixed(0)}%</span><small>{formatMoney(topCategory.amount)}</small></div></div><div className="finance-category-ranks">{categories.slice(0, 7).map((item, index) => <article key={item.category}><em>{String(index + 1).padStart(2, "0")}</em><span>{item.category}</span><i><span style={{ width: `${item.amount / categories[0].amount * 100}%` }} /></i><strong>{formatMoney(item.amount)}</strong></article>)}</div></> : <p className="finance-empty-copy">No spending recorded for this {scope}.</p>}</section>
      <section className="finance-panel finance-snapshot-list"><header><div><span className="text-label">Saved history</span><h3>Net worth snapshots</h3></div><small>{snapshots.length} saved</small></header><div>{[...snapshots].reverse().slice(0, 8).map((item) => { const adjustedNetWorth = item.accounts.filter((account) => account.type !== "credit").reduce((total, account) => total + account.balance, 0); return <article key={item.id}><span className={item.source === "manual" ? "is-manual" : ""}>{item.source === "manual" ? "◆" : "○"}</span><div><strong>{new Date(`${item.date}T12:00:00`).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</strong><small>{item.source === "manual" ? "Manual checkpoint" : "Monthly snapshot"} · {item.accounts.filter((account) => account.type !== "credit").length} accounts</small></div><b className="finance-balance-value">{formatMoney(adjustedNetWorth)}</b>{item.source === "manual" && <button type="button" aria-label="Delete net worth snapshot" onClick={() => onDeleteSnapshot(item)}>×</button>}</article>; })}</div></section></div>
  </section>;
}
