import { useState } from "react";

import type { FinanceBudgetAllocation, FinanceBudgetMonth, FinanceCategory, FinanceSubcategory, FinanceTransaction } from "../../../database/db";
import { formatMoney, getMonthSummary } from "../services/financeCalculations";
import { calculateBudgetRows } from "../services/financeBudgetService";

interface Props {
  now: Date; categories: FinanceCategory[]; subcategories: FinanceSubcategory[]; months: FinanceBudgetMonth[]; allocations: FinanceBudgetAllocation[]; transactions: FinanceTransaction[];
  onSetExpectedIncome: (month: string, amount: number) => Promise<void>; onSetAllocation: (month: string, subcategoryId: number, amount: number) => Promise<void>; onCopyPrevious: (month: string) => Promise<number>; onManageCategories: () => void;
}
function monthKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; }
function shiftMonth(month: string, offset: number) { const [year, number] = month.split("-").map(Number); const date = new Date(year, number - 1 + offset, 1); return monthKey(date); }
function monthLabel(month: string) { const [year, number] = month.split("-").map(Number); return new Date(year, number - 1, 1).toLocaleDateString("en-US", { month: "long", year: "numeric" }); }

export default function FinanceBudget(props: Props) {
  const [month, setMonth] = useState(monthKey(props.now)); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const budgetMonth = props.months.find((item) => item.month === month); const rows = calculateBudgetRows(month, props.allocations, props.subcategories, props.transactions);
  const actual = getMonthSummary(props.transactions, month); const budgeted = rows.reduce((total, row) => total + row.available, 0); const totalSpent = actual.expenses; const remaining = budgeted - totalSpent;
  const activeCategories = props.categories.filter((item) => !item.deletedAt && item.name !== "Income").sort((a, b) => a.sortOrder - b.sortOrder);
  async function copyPrevious() { setError(""); setNotice(""); try { const count = await props.onCopyPrevious(month); setNotice(`${count} ${count === 1 ? "allocation" : "allocations"} copied.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not copy the previous budget."); } }
  return <section className="finance-budget-view">
    <header className="finance-section-heading"><div><span className="text-label">Monthly intention</span><h2>Budget</h2><p>Give your money direction without turning spending into guilt.</p></div><div className="finance-budget-month"><button type="button" onClick={() => setMonth(shiftMonth(month, -1))}>←</button><strong>{monthLabel(month)}</strong><button type="button" onClick={() => setMonth(shiftMonth(month, 1))}>→</button></div></header>
    <section className="finance-budget-summary finance-panel"><article><span>Expected income</span><div className="finance-inline-money"><i>$</i><input key={`${month}:${budgetMonth?.expectedIncome}`} defaultValue={budgetMonth?.expectedIncome ?? 0} inputMode="decimal" onBlur={(event) => props.onSetExpectedIncome(month, Number(event.target.value))} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }} /></div><small>Monthly plan</small></article><article><span>Actual income</span><strong className="is-positive">{formatMoney(actual.income)}</strong><small>From transactions</small></article><article><span>Budgeted</span><strong>{formatMoney(budgeted)}</strong><small>{rows.filter((row) => row.available > 0).length} active allocations</small></article><article><span>Spent</span><strong>{formatMoney(totalSpent)}</strong><small>From expenses</small></article><article><span>Remaining</span><strong className={remaining >= 0 ? "is-positive" : "is-negative"}>{formatMoney(remaining)}</strong><small>{budgeted > 0 ? `${Math.round(totalSpent / budgeted * 100)}% used` : "Set your first allocation"}</small></article></section>
    <div className="finance-budget-actions"><button type="button" onClick={copyPrevious}>Copy last month</button><button type="button" onClick={props.onManageCategories}>Manage categories</button>{notice && <small className="is-positive">{notice}</small>}{error && <small className="is-negative">{error}</small>}</div>
    <div className="finance-budget-groups">{activeCategories.map((category) => {
      const categorySubs = props.subcategories.filter((item) => item.categoryId === category.id && !item.deletedAt).sort((a, b) => a.sortOrder - b.sortOrder); if (!categorySubs.length) return null;
      const categoryRows = categorySubs.map((subcategory) => rows.find((row) => row.subcategoryId === subcategory.id)); const categoryBudget = categoryRows.reduce((total, row) => total + (row?.available ?? 0), 0); const categorySpent = categoryRows.reduce((total, row) => total + (row?.spent ?? 0), 0);
      return <section className="finance-budget-group finance-panel" key={category.id}><header><div><span className="finance-category-index">{String(category.sortOrder + 1).padStart(2, "0")}</span><div><h3>{category.name}</h3><small>{formatMoney(categorySpent)} of {formatMoney(categoryBudget)}</small></div></div><strong className={categoryBudget - categorySpent < 0 ? "is-negative" : ""}>{formatMoney(categoryBudget - categorySpent)}</strong></header><div>{categorySubs.map((subcategory) => { const row = rows.find((item) => item.subcategoryId === subcategory.id); const spent = row?.spent ?? props.transactions.filter((item) => !item.deletedAt && item.type === "expense" && item.date.startsWith(month) && item.subcategoryId === subcategory.id).reduce((total, item) => total + item.amount, 0); const available = row?.available ?? 0; const percentage = available > 0 ? spent / available * 100 : spent > 0 ? 100 : 0; const over = spent > available && spent > 0;
        return <article key={subcategory.id} className={over ? "is-over" : ""}><div><strong>{subcategory.name}</strong><small>{spent ? `${formatMoney(spent)} spent` : "No spending"}</small></div><div className="finance-budget-progress"><i><span style={{ width: `${Math.min(100, percentage)}%` }} /></i><small>{available ? `${Math.round(percentage)}%` : spent ? "Unbudgeted" : "Not set"}</small></div><label><span>$</span><input key={`${month}:${subcategory.id}:${row?.baseAmount}`} defaultValue={row?.baseAmount || ""} inputMode="decimal" placeholder="0" onBlur={(event) => props.onSetAllocation(month, subcategory.id!, Number(event.target.value))} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }} /></label><b className={over ? "is-negative" : ""}>{available ? over ? `${formatMoney(spent - available)} over` : `${formatMoney(available - spent)} left` : "—"}</b></article>;
      })}</div></section>;
    })}</div>
  </section>;
}
