import { useState } from "react";

import type { FinanceAccount, FinanceCategory, FinanceNetWorthSnapshot, FinanceTransaction } from "../../../database/db";
import { accountTypeLabel } from "../financeCatalog";
import { formatMoney, getAccountBalances, getCategorySpending, getSixMonthCashFlow } from "../services/financeCalculations";

type Range = "3m" | "6m" | "ytd" | "1y" | "all";
interface Props { now: Date; accounts: FinanceAccount[]; categories: FinanceCategory[]; transactions: FinanceTransaction[]; snapshots: FinanceNetWorthSnapshot[]; onSaveSnapshot: () => Promise<void>; onDeleteSnapshot: (snapshot: FinanceNetWorthSnapshot) => Promise<void>; }
function cutoffFor(range: Range, now: Date) { if (range === "all") return "0000-00-00"; if (range === "ytd") return `${now.getFullYear()}-01-01`; const months = range === "3m" ? 3 : range === "6m" ? 6 : 12; const date = new Date(now.getFullYear(), now.getMonth() - months + 1, 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-01`; }
function chartPoints(values: number[], width = 680, height = 180) { if (!values.length) return ""; const min = Math.min(...values); const max = Math.max(...values); return values.map((value, index) => `${values.length === 1 ? width / 2 : index / (values.length - 1) * width},${height - ((value - min) / Math.max(1, max - min)) * (height - 28) - 14}`).join(" "); }

export default function FinanceReports({ now, accounts, categories: categoryRecords, transactions, snapshots, onSaveSnapshot, onDeleteSnapshot }: Props) {
  const [range, setRange] = useState<Range>("1y"); const [accountId, setAccountId] = useState<number | "all">("all"); const [saving, setSaving] = useState(false);
  const filtered = snapshots.filter((item) => item.date >= cutoffFor(range, now)); const currentBalances = getAccountBalances(accounts, transactions); const currentNetWorth = currentBalances.reduce((total, item) => total + item.balance, 0);
  const values = accountId === "all" ? filtered.map((item) => item.netWorth) : filtered.map((item) => item.accounts.find((account) => account.accountId === accountId)?.balance).filter((value): value is number => value !== undefined);
  const currentValue = accountId === "all" ? currentNetWorth : currentBalances.find((item) => item.account.id === accountId)?.balance ?? 0; const firstValue = values[0] ?? currentValue; const change = currentValue - firstValue;
  const flow = getSixMonthCashFlow(transactions, now); const categories = getCategorySpending(transactions, `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`, categoryRecords); const flowMax = Math.max(1, ...flow.flatMap((item) => [item.income, item.expenses]));
  return <section className="finance-reports-view">
    <header className="finance-section-heading"><div><span className="text-label">History, preserved</span><h2>Reports</h2><p>See where your financial position has actually moved.</p></div><div className="finance-report-actions"><select value={range} onChange={(event) => setRange(event.target.value as Range)}><option value="3m">3 months</option><option value="6m">6 months</option><option value="ytd">YTD</option><option value="1y">1 year</option><option value="all">All time</option></select><button type="button" disabled={saving || !accounts.length} onClick={async () => { setSaving(true); try { await onSaveSnapshot(); } finally { setSaving(false); } }}>{saving ? "Saving…" : "Save snapshot now"}</button></div></header>
    <section className="finance-report-hero finance-panel"><header><div><span className="text-label">{accountId === "all" ? "Net worth history" : "Account balance history"}</span><select value={accountId} onChange={(event) => setAccountId(event.target.value === "all" ? "all" : Number(event.target.value))}><option value="all">All accounts</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><strong>{formatMoney(currentValue)}</strong><small className={change >= 0 ? "is-positive" : "is-negative"}>{change >= 0 ? "+" : ""}{formatMoney(change)} during period</small></div></header><div className="finance-net-worth-chart"><svg viewBox="0 0 680 180" preserveAspectRatio="none" role="img" aria-label="Financial history line"><defs><linearGradient id="finance-chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7fae91" stopOpacity=".2"/><stop offset="1" stopColor="#7fae91" stopOpacity="0"/></linearGradient></defs>{values.length > 1 && <polygon points={`0,180 ${chartPoints(values)} 680,180`} fill="url(#finance-chart-fill)" />}<polyline points={chartPoints(values.length ? values : [currentValue])} fill="none" stroke="#8db89b" strokeWidth="2" vectorEffect="non-scaling-stroke" />{(values.length ? values : [currentValue]).map((value, index, list) => { const point = chartPoints(list).split(" ")[index].split(","); return <circle key={`${value}-${index}`} cx={point[0]} cy={point[1]} r="3" fill="#b5d2bf" />; })}</svg><footer>{filtered.length ? filtered.map((item) => <span key={item.id}>{new Date(`${item.date}T12:00:00`).toLocaleDateString("en-US", { month: "short", year: "2-digit" })}</span>) : <span>Save your first snapshot to begin history.</span>}</footer></div></section>
    <div className="finance-report-grid"><section className="finance-panel finance-report-accounts"><header><div><span className="text-label">Current position</span><h3>Account balances</h3></div><small>{accounts.length} accounts</small></header><div>{currentBalances.map(({ account, balance }) => { const earliest = filtered.map((item) => item.accounts.find((entry) => entry.accountId === account.id)?.balance).find((value) => value !== undefined); const delta = earliest === undefined ? 0 : balance - earliest; return <button type="button" key={account.id} onClick={() => setAccountId(account.id!)}><span className={`finance-account-dot type-${account.type}`} /><div><strong>{account.name}</strong><small>{accountTypeLabel(account.type)}</small></div><b>{formatMoney(balance)}</b><i className={delta >= 0 ? "is-positive" : "is-negative"}>{delta >= 0 ? "+" : ""}{formatMoney(delta, true)}</i></button>; })}</div></section>
      <section className="finance-panel finance-report-flow"><header><div><span className="text-label">Cash flow</span><h3>Income vs. spending</h3></div><small>Six months</small></header><div className="finance-report-bars">{flow.map((item) => <span key={item.month}><i className="income" style={{ height: `${item.income / flowMax * 100}%` }} /><i className="expense" style={{ height: `${item.expenses / flowMax * 100}%` }} /><small>{item.label}</small></span>)}</div><footer><span><i className="income" /> Income</span><span><i className="expense" /> Spending</span></footer></section>
    </div>
    <div className="finance-report-grid"><section className="finance-panel finance-report-categories"><header><div><span className="text-label">This month</span><h3>Spending distribution</h3></div></header>{categories.length ? <div>{categories.map((item) => <article key={item.category}><span>{item.category}</span><i><span style={{ width: `${item.amount / categories[0].amount * 100}%` }} /></i><strong>{formatMoney(item.amount)}</strong></article>)}</div> : <p className="finance-empty-copy">No spending recorded this month.</p>}</section>
      <section className="finance-panel finance-snapshot-list"><header><div><span className="text-label">Saved history</span><h3>Snapshots</h3></div><small>{snapshots.length} saved</small></header><div>{[...snapshots].reverse().slice(0, 8).map((item) => <article key={item.id}><span className={item.source === "manual" ? "is-manual" : ""}>{item.source === "manual" ? "◆" : "○"}</span><div><strong>{new Date(`${item.date}T12:00:00`).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</strong><small>{item.source === "manual" ? "Manual checkpoint" : "Monthly snapshot"} · {item.accounts.length} accounts</small></div><b>{formatMoney(item.netWorth)}</b>{item.source === "manual" && <button type="button" onClick={() => onDeleteSnapshot(item)}>×</button>}</article>)}</div></section></div>
  </section>;
}
